// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AppointmentInput struct {
	PatientID      string  `json:"patient_id"`
	PractitionerID string  `json:"practitioner_id"`
	ScheduledStart string  `json:"scheduled_start"`
	ScheduledEnd   string  `json:"scheduled_end"`
	Note           *string `json:"note,omitempty"`
	SlotID         *string `json:"slot_id,omitempty"`
}

type AppointmentSlotsFilter struct {
	BranchID       *string `json:"branch_id,omitempty"`
	PractitionerID *string `json:"practitioner_id,omitempty"`
	SlotDate       *string `json:"slot_date,omitempty"`
	Status         *string `json:"status,omitempty"`
}

type AppointmentUpdateInput struct {
	Status *string `json:"status,omitempty"`
	Note   *string `json:"note,omitempty"`
}

type AppointmentsFilter struct {
	BranchID       *string `json:"branch_id,omitempty"`
	PatientID      *string `json:"patient_id,omitempty"`
	PractitionerID *string `json:"practitioner_id,omitempty"`
	Status         *string `json:"status,omitempty"`
	ScheduledStart *string `json:"scheduled_start,omitempty"`
	ScheduledEnd   *string `json:"scheduled_end,omitempty"`
}

type BranchHoursInput struct {
	DayOfWeek int     `json:"day_of_week"`
	OpenTime  *string `json:"open_time,omitempty"`
	CloseTime *string `json:"close_time,omitempty"`
}

type BranchHoursUpdateInput struct {
	DayOfWeek *int    `json:"day_of_week,omitempty"`
	OpenTime  *string `json:"open_time,omitempty"`
	CloseTime *string `json:"close_time,omitempty"`
	IsActive  *bool   `json:"is_active,omitempty"`
}

type Mutation struct {
}

type Patient struct {
	ID string `json:"id"`
}

func (Patient) IsEntity() {}

type PractitionerAvailabilityInput struct {
	PractitionerID string `json:"practitioner_id"`
	StartTime      string `json:"start_time"`
	EndTime        string `json:"end_time"`
}

type PractitionerBranchInput struct {
	PractitionerID string  `json:"practitioner_id"`
	Role           *string `json:"role,omitempty"`
}

type Query struct {
}

type ScheduleExceptionInput struct {
	PractitionerID string `json:"practitioner_id"`
	ExceptionDate  string `json:"exception_date"`
}

type ScheduleTemplateInput struct {
	PractitionerID      string  `json:"practitioner_id"`
	TemplateName        string  `json:"template_name"`
	DayOfWeek           int     `json:"day_of_week"`
	StartTime           string  `json:"start_time"`
	EndTime             string  `json:"end_time"`
	SlotDurationMinutes int     `json:"slot_duration_minutes"`
	BreakStart          *string `json:"break_start,omitempty"`
	BreakEnd            *string `json:"break_end,omitempty"`
}

type ScheduleTemplateUpdateInput struct {
	TemplateName        *string `json:"template_name,omitempty"`
	DayOfWeek           *int    `json:"day_of_week,omitempty"`
	StartTime           *string `json:"start_time,omitempty"`
	EndTime             *string `json:"end_time,omitempty"`
	SlotDurationMinutes *int    `json:"slot_duration_minutes,omitempty"`
	BreakStart          *string `json:"break_start,omitempty"`
	BreakEnd            *string `json:"break_end,omitempty"`
	IsActive            *bool   `json:"is_active,omitempty"`
}

type User struct {
	ID string `json:"id"`
}

func (User) IsEntity() {}
