package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/clinicmanager/services/user/graph/generated"
	"github.com/clinicmanager/services/user/graph/model"
)

// FindBranchByID is the resolver for the findBranchByID field.
func (r *entityResolver) FindBranchByID(ctx context.Context, id string) (*model.Branch, error) {
	return r.UserService.GetBranchByID(ctx, id)
}

// FindPermissionByID is the resolver for the findPermissionByID field.
func (r *entityResolver) FindPermissionByID(ctx context.Context, id string) (*model.Permission, error) {
	return r.UserService.GetPermissionByID(ctx, id)
}

// FindRoleByID is the resolver for the findRoleByID field.
func (r *entityResolver) FindRoleByID(ctx context.Context, id string) (*model.Role, error) {
	return r.UserService.GetRoleByID(ctx, id)
}

// FindTenantByID is the resolver for the findTenantByID field.
func (r *entityResolver) FindTenantByID(ctx context.Context, id string) (*model.Tenant, error) {
	return r.UserService.GetTenantByID(ctx, id)
}

// FindUserByID is used by Apollo Federation to resolve a User entity by its primary key.
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (*model.User, error) {
	return r.UserService.GetUserByID(ctx, id)
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
