package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"strconv"

	"github.com/clinicmanager/services/user/graph/generated"
	"github.com/clinicmanager/services/user/graph/model"
)

// FindAppRoleByID is the resolver for the findAppRoleByID field.
func (r *entityResolver) FindAppRoleByID(ctx context.Context, id string) (*model.AppRole, error) {
	idInt, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}
	role, err := r.UserService.GetAppRoleByID(ctx, idInt)
	if err != nil {
		return nil, err
	}
	roleID := strconv.Itoa(role.ID)
	return &model.AppRole{
		ID:          roleID,
		Name:        role.Name,
		Description: &role.Description,
	}, nil
}

// FindUserByID is used by Apollo Federation to resolve a User entity by its primary key.
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (*model.User, error) {
	return r.UserService.FindUserByID(ctx, id)
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
