package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/clinicmanager/services/user/graph/generated"
	"github.com/clinicmanager/services/user/graph/model"
)

// Me returns the currently authenticated user with all their tenant/branch assignments.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return r.UserService.GetMe(ctx)
}

// User returns a user by ID scoped to the caller's tenant.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	return r.UserService.GetUserByID(ctx, id)
}

// MyAssignments returns all branch assignments for the currently authenticated user.
func (r *queryResolver) MyAssignments(ctx context.Context) ([]*model.UserBranchAssignment, error) {
	return r.UserService.GetMyAssignments(ctx)
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
