type AppRole @key(fields: "id") {
  id: ID!
  name: String!
  description: String
  createdAt: String!
  createdBy: String
  createdAction: String
  updatedAt: String
  updatedBy: String
  updatedAction: String
}

type User @key(fields: "id") {
  id: ID!
  email: String!
  name: String!
  isActive: Boolean!
  lastLogin: String
  appRoles: [AppRole!]!
  isValidated: Boolean!
  validatedAt: String
  createdAt: String!
  updatedAt: String!
  createdBy: String
  updatedBy: String
  createdAction: String
  updatedAction: String
}

type Query {
  meUser: User!
  user(id: ID!): User
}
