services:
  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki/config.yml:/etc/loki/config.yml
    command: -config.file=/etc/loki/config.yml

  promtail:
    image: grafana/promtail:2.9.8
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./monitoring/promtail/config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki

  db:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: clinic_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  router:
    image: ghcr.io/apollographql/router:v1.45.0
    container_name: apollo_router
    ports:
      - "4000:4000"
    volumes:
      - ./rover/supergraph.graphql:/dist/config/supergraph.graphql
      - ./rover/router.yaml:/dist/config/router.yaml
    command: -s /dist/config/supergraph.graphql -c /dist/config/router.yaml
    depends_on:
      - user

  user:
    build:
      context: .
      dockerfile: services/user/Dockerfile
    image: clinic/user:latest
    container_name: user
    restart: unless-stopped
    env_file:
      - .env
    environment:
      USERDB_URL: postgres://postgres:1@db:5432/user?sslmode=disable
      IN_DOCKER: "true"
    ports:
      - "8081:8081"
    volumes:
      - ./.env:/app/.env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  grafana-data:
