federation_version: 2
subgraphs:
  user:
    routing_url: http://user:8081/graphql
    schema:
      file: ./services/user/graph/schema.graphqls
  tenant:
    routing_url: http://tenant:8082/graphql
    schema:
      file: ./services/tenant/graph/schema.graphqls
