// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MessageInput struct {
	ThreadID string `json:"thread_id"`
	Body     string `json:"body"`
	Nonce    string `json:"nonce"`
}

type Mutation struct {
}

type ParticipantInput struct {
	ThreadID      string `json:"thread_id"`
	ParticipantID string `json:"participant_id"`
	Role          string `json:"role"`
}

type ParticipantRefInput struct {
	ParticipantID string `json:"participant_id"`
	Role          string `json:"role"`
}

type Query struct {
}

type ThreadInput struct {
	Title        string                 `json:"title"`
	Type         string                 `json:"type"`
	Participants []*ParticipantRefInput `json:"participants"`
	Keys         []*ThreadKeyInput      `json:"keys"`
}

type ThreadKeyInput struct {
	UserID       string `json:"user_id"`
	EncryptedKey string `json:"encrypted_key"`
}

type ThreadUpdateInput struct {
	Type     *string `json:"type,omitempty"`
	IsActive *bool   `json:"is_active,omitempty"`
}
