// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/clinicmanager/services/tenant/db"
)

type Query struct {
}

type TenantUserAssignment struct {
	ID            string            `json:"id"`
	UserID        string            `json:"userId"`
	Branch        *db.BunBranch     `json:"branch"`
	Tenant        *db.BunTenant     `json:"tenant"`
	Role          *db.BunTenantRole `json:"role"`
	AssignedBy    *string           `json:"assignedBy,omitempty"`
	AssignedAt    string            `json:"assignedAt"`
	UpdatedAt     *string           `json:"updatedAt,omitempty"`
	UpdatedBy     *string           `json:"updatedBy,omitempty"`
	UpdatedAction *string           `json:"updatedAction,omitempty"`
	IsActive      bool              `json:"isActive"`
}

type User struct {
	ID          string                  `json:"id"`
	Assignments []*TenantUserAssignment `json:"assignments"`
}

func (User) IsEntity() {}
