// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/clinicmanager/services/tenant/db"
)

type AddressInput struct {
	Address   string  `json:"address"`
	Baranggay *string `json:"baranggay,omitempty"`
	City      string  `json:"city"`
	State     string  `json:"state"`
	ZipCode   string  `json:"zipCode"`
	Country   *string `json:"country,omitempty"`
}

type BranchInput struct {
	Name     string  `json:"name"`
	Timezone string  `json:"timezone"`
	Phone    *string `json:"phone,omitempty"`
	IsActive bool    `json:"isActive"`
}

type CreateTenantRoleInput struct {
	Name        string  `json:"name"`
	BranchID    string  `json:"branchId"`
	Description *string `json:"description,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type SetRolePermissionsInput struct {
	RoleID        string   `json:"roleId"`
	PermissionIds []string `json:"permissionIds"`
}

type TenantInvite struct {
	ID         string            `json:"id"`
	Email      string            `json:"email"`
	Branch     *db.BunBranch     `json:"branch"`
	Role       *db.BunTenantRole `json:"role"`
	Status     string            `json:"status"`
	InvitedAt  string            `json:"invitedAt"`
	AcceptedAt *string           `json:"acceptedAt,omitempty"`
	ExpiresAt  string            `json:"expiresAt"`
}

type TenantUserAssignment struct {
	ID            string            `json:"id"`
	UserID        string            `json:"userId"`
	Branch        *db.BunBranch     `json:"branch"`
	Tenant        *db.BunTenant     `json:"tenant"`
	Role          *db.BunTenantRole `json:"role"`
	AssignedBy    *string           `json:"assignedBy,omitempty"`
	AssignedAt    string            `json:"assignedAt"`
	UpdatedAt     *string           `json:"updatedAt,omitempty"`
	UpdatedBy     *string           `json:"updatedBy,omitempty"`
	UpdatedAction *string           `json:"updatedAction,omitempty"`
	IsActive      bool              `json:"isActive"`
}

type UpdateAssignmentInput struct {
	RoleID string `json:"roleId"`
}

type User struct {
	ID          string                  `json:"id"`
	Assignments []*TenantUserAssignment `json:"assignments"`
}

func (User) IsEntity() {}
