package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/clinicmanager/services/messaging/db"
	"github.com/clinicmanager/services/messaging/graph/generated"
)

// FindMessageByID is the resolver for the findMessageByID field.
func (r *entityResolver) FindMessageByID(ctx context.Context, id string) (*db.BunMessage, error) {
	return r.MessagingService.GetMessageByID(ctx, id)
}

// FindMessageParticipantByID is the resolver for the findMessageParticipantByID field.
func (r *entityResolver) FindMessageParticipantByID(ctx context.Context, id string) (*db.BunMessageParticipant, error) {
	return r.MessagingService.Repo.FindParticipantByID(ctx, id)
}

// FindMessageThreadByID is the resolver for the findMessageThreadByID field.
func (r *entityResolver) FindMessageThreadByID(ctx context.Context, id string) (*db.BunMessageThread, error) {
	return r.MessagingService.GetThreadByID(ctx, id)
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
