package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"time"

	"github.com/clinicmanager/services/messaging/db"
	"github.com/clinicmanager/services/messaging/graph/generated"
	"github.com/clinicmanager/services/messaging/graph/model"
)

// CreatedAt is the resolver for the created_at field.
func (r *messageResolver) CreatedAt(ctx context.Context, obj *db.BunMessage) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *messageResolver) UpdatedAt(ctx context.Context, obj *db.BunMessage) (string, error) {
	return obj.UpdatedAt.Format(time.RFC3339), nil
}

// LastReadAt is the resolver for the last_read_at field.
func (r *messageParticipantResolver) LastReadAt(ctx context.Context, obj *db.BunMessageParticipant) (string, error) {
	return obj.LastReadAt.Format(time.RFC3339), nil
}

// Messages is the resolver for the messages field.
func (r *messageThreadResolver) Messages(ctx context.Context, obj *db.BunMessageThread) ([]*db.BunMessage, error) {
	return r.MessagingService.GetMessagesByThread(ctx, obj.ID)
}

// Participants is the resolver for the participants field.
func (r *messageThreadResolver) Participants(ctx context.Context, obj *db.BunMessageThread) ([]*db.BunMessageParticipant, error) {
	return r.MessagingService.GetParticipantsByThread(ctx, obj.ID)
}

// CreatedAt is the resolver for the created_at field.
func (r *messageThreadResolver) CreatedAt(ctx context.Context, obj *db.BunMessageThread) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *messageThreadResolver) UpdatedAt(ctx context.Context, obj *db.BunMessageThread) (string, error) {
	return obj.UpdatedAt.Format(time.RFC3339), nil
}

// CreateThread is the resolver for the createThread field.
func (r *mutationResolver) CreateThread(ctx context.Context, input model.ThreadInput) (*db.BunMessageThread, error) {
	return r.MessagingService.CreateThread(ctx, input)
}

// UpdateThread is the resolver for the updateThread field.
func (r *mutationResolver) UpdateThread(ctx context.Context, id string, input model.ThreadUpdateInput) (*db.BunMessageThread, error) {
	return r.MessagingService.UpdateThread(ctx, id, input)
}

// DeleteThread is the resolver for the deleteThread field.
func (r *mutationResolver) DeleteThread(ctx context.Context, id string) (bool, error) {
	return r.MessagingService.DeleteThread(ctx, id)
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, input model.MessageInput) (*db.BunMessage, error) {
	return r.MessagingService.SendMessage(ctx, input)
}

// DeleteMessage is the resolver for the deleteMessage field.
func (r *mutationResolver) DeleteMessage(ctx context.Context, id string) (bool, error) {
	return r.MessagingService.DeleteMessage(ctx, id)
}

// AddParticipant is the resolver for the addParticipant field.
func (r *mutationResolver) AddParticipant(ctx context.Context, input model.ParticipantInput) (*db.BunMessageParticipant, error) {
	return r.MessagingService.AddParticipant(ctx, input)
}

// RemoveParticipant is the resolver for the removeParticipant field.
func (r *mutationResolver) RemoveParticipant(ctx context.Context, id string) (bool, error) {
	return r.MessagingService.RemoveParticipant(ctx, id)
}

// Thread is the resolver for the thread field.
func (r *queryResolver) Thread(ctx context.Context, id string) (*db.BunMessageThread, error) {
	return r.MessagingService.GetThreadByID(ctx, id)
}

// ThreadsByParticipant is the resolver for the threadsByParticipant field.
func (r *queryResolver) ThreadsByParticipant(ctx context.Context, participantID *string) ([]*db.BunMessageThread, error) {
	return r.MessagingService.GetThreadsByParticipant(ctx, participantID)
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, threadID string) ([]*db.BunMessage, error) {
	return r.MessagingService.GetMessagesByThread(ctx, threadID)
}

// Participants is the resolver for the participants field.
func (r *queryResolver) Participants(ctx context.Context, threadID string) ([]*db.BunMessageParticipant, error) {
	return r.MessagingService.GetParticipantsByThread(ctx, threadID)
}

// Message returns generated.MessageResolver implementation.
func (r *Resolver) Message() generated.MessageResolver { return &messageResolver{r} }

// MessageParticipant returns generated.MessageParticipantResolver implementation.
func (r *Resolver) MessageParticipant() generated.MessageParticipantResolver {
	return &messageParticipantResolver{r}
}

// MessageThread returns generated.MessageThreadResolver implementation.
func (r *Resolver) MessageThread() generated.MessageThreadResolver { return &messageThreadResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	messageResolver            struct{ *Resolver }
	messageParticipantResolver struct{ *Resolver }
	messageThreadResolver      struct{ *Resolver }
	mutationResolver           struct{ *Resolver }
	queryResolver              struct{ *Resolver }
)
