type MessageThread @key(fields: "id") {
  id: ID!
  branch_id: ID!
  title: String!
  type: String!
  is_active: Boolean!
  messages: [Message!]!
  participants: [MessageParticipant!]!
  threadKey: String
  created_at: String!
  updated_at: String!
}

type Message @key(fields: "id") {
  id: ID!
  thread_id: ID!
  sender_id: ID!
  body: String!
  nonce: String!
  is_active: Boolean!
  created_at: String!
  updated_at: String!
}

type MessageParticipant @key(fields: "id") {
  id: ID!
  thread_id: ID!
  participant_id: ID!
  role: String!
  last_read_at: String!
  is_active: Boolean!
}

input ThreadKeyInput {
  user_id: ID!
  encrypted_key: String!
}

input ThreadInput {
  title: String!
  type: String!
  participants: [ParticipantRefInput!]!
  keys: [ThreadKeyInput!]!
}

input ParticipantRefInput {
  participant_id: ID!
  role: String!
}

input ThreadUpdateInput {
  type: String
  is_active: Boolean
}

input MessageInput {
  thread_id: ID!
  body: String!
  nonce: String!
}

input ParticipantInput {
  thread_id: ID!
  participant_id: ID!
  role: String!
}

type Query {
  thread(id: ID!): MessageThread
  threadsByParticipant(participant_id: ID): [MessageThread!]!
  messages(thread_id: ID!): [Message!]!
  participants(thread_id: ID!): [MessageParticipant!]!
  userPublicKey(user_id: ID!): String
  threadKey(thread_id: ID!): String
}

type Mutation {
  createThread(input: ThreadInput!): MessageThread!
  updateThread(id: ID!, input: ThreadUpdateInput!): MessageThread!
  deleteThread(id: ID!): Boolean!
  sendMessage(input: MessageInput!): Message!
  deleteMessage(id: ID!): Boolean!
  addParticipant(input: ParticipantInput!): MessageParticipant!
  removeParticipant(id: ID!): Boolean!
  registerPublicKey(public_key: String!): Boolean!
}
