package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/clinicmanager/services/tenant/db"
	"github.com/clinicmanager/services/tenant/graph/generated"
	"github.com/clinicmanager/services/tenant/graph/model"
)

// FindBranchByID is the resolver for the findBranchByID field.
func (r *entityResolver) FindBranchByID(ctx context.Context, id string) (*db.BunBranch, error) {
	return r.TenantService.GetBranchByID(ctx, id)
}

// FindTenantByID is the resolver for the findTenantByID field.
func (r *entityResolver) FindTenantByID(ctx context.Context, id string) (*db.BunTenant, error) {
	return r.TenantService.GetTenantByID(ctx, id)
}

// FindTenantPermissionByID is the resolver for the findTenantPermissionByID field.
func (r *entityResolver) FindTenantPermissionByID(ctx context.Context, id string) (*db.BunTenantPermission, error) {
	return r.TenantService.GetPermissionByID(ctx, id)
}

// FindTenantRoleByID is the resolver for the findTenantRoleByID field.
// Permissions are resolved lazily via the TenantRole field resolver.
func (r *entityResolver) FindTenantRoleByID(ctx context.Context, id string) (*db.BunTenantRole, error) {
	return r.TenantService.GetRoleByID(ctx, id)
}

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (*model.User, error) {
	aa, err := r.TenantService.GetAssignmentsByUser(ctx, id)
	if err != nil {
		return nil, err
	}
	return &model.User{ID: id, Assignments: aa}, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
