type Tenant @key(fields: "id") {
  id: ID!
  name: String!
  slug: String!
  domain: String
  status: String!
}

type Address @key(fields: "id") {
  id: ID!
  address: String!
  baranggay: String!
  city: String!
  state: String!
  zipCode: String!
  country: String!
}

type Branch @key(fields: "id") {
  id: ID!
  tenantId: String!
  name: String!
  address: Address
  timezone: String!
  phone: String
  isActive: Boolean!
}

type TenantRole @key(fields: "id") {
  id: ID!
  name: String!
  description: String
  isSystemRole: Boolean!
  tenantId: String
  permissions: [TenantPermission!]!
}

type TenantPermission @key(fields: "id") {
  id: ID!
  resource: String!
  action: String!
  scope: String!
  description: String
}

type TenantUserAssignment {
  id: ID!
  userId: String!
  branch: Branch!
  tenant: Tenant!
  role: TenantRole!
  assignedBy: String
  assignedAt: String!
  updatedAt: String
  updatedBy: String
  updatedAction: String
  isActive: Boolean!
}

extend type User @key(fields: "id") {
  id: ID! @external
  assignments: [TenantUserAssignment!]!
}

type Query {
  meTenant: User!
  tenant(id: ID!): Tenant
  branch(id: ID!): Branch
  address(id: ID!): Address
  tenantRole(id: ID!): TenantRole
  tenantPermission(id: ID!): TenantPermission
  myAssignments: [TenantUserAssignment!]!
  assignmentsByUser(userId: ID!): [TenantUserAssignment!]!
}

type Mutation {
  createTenantAddress(input: AddressInput!): Address!
  updateTenantAddress(id: ID!, input: AddressInput!): Address!
  updateBranch(id: ID!, input: BranchInput!): Branch!
}

input AddressInput {
  address: String!
  baranggay: String
  city: String!
  state: String!
  zipCode: String!
  country: String
}

input BranchInput {
  name: String!
  timezone: String!
  phone: String
  isActive: Boolean!
}
