package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	"github.com/clinicmanager/services/tenant/db"
	"github.com/clinicmanager/services/tenant/graph/generated"
	"github.com/clinicmanager/services/tenant/graph/model"
	sharedctx "github.com/clinicmanager/shared/context"
)

// Address is the resolver for the address field.
func (r *branchResolver) Address(ctx context.Context, obj *db.BunBranch) (*db.BunAddress, error) {
	if obj.AddressID == nil {
		return nil, nil
	}
	return r.TenantService.GetAddressByID(ctx, *obj.AddressID)
}

// CreateAddress is the resolver for the createAddress field.
func (r *mutationResolver) CreateAddress(ctx context.Context, input model.AddressInput) (*db.BunAddress, error) {
	ct := sharedctx.FromContext(ctx)
	baranggay := ""
	if input.Baranggay != nil {
		baranggay = *input.Baranggay
	}
	country := "Philippines"
	if input.Country != nil {
		country = *input.Country
	}
	addr := &db.BunAddress{
		Address:   input.Address,
		Baranggay: baranggay,
		City:      input.City,
		State:     input.State,
		ZipCode:   input.ZipCode,
		Country:   country,
	}
	if ct.UserID != "" {
		addr.CreatedBy = &ct.UserID
		addr.UpdatedBy = &ct.UserID
	}
	if err := r.TenantService.CreateAddress(ctx, addr); err != nil {
		return nil, err
	}
	return addr, nil
}

// UpdateAddress is the resolver for the updateAddress field.
func (r *mutationResolver) UpdateAddress(ctx context.Context, id string, input model.AddressInput) (*db.BunAddress, error) {
	addr, err := r.TenantService.GetAddressByID(ctx, id)
	if err != nil || addr == nil {
		if addr == nil {
			return nil, fmt.Errorf("address not found")
		}
		return nil, err
	}
	baranggay := ""
	if input.Baranggay != nil {
		baranggay = *input.Baranggay
	}
	country := "Philippines"
	if input.Country != nil {
		country = *input.Country
	}
	addr.Address = input.Address
	addr.Baranggay = baranggay
	addr.City = input.City
	addr.State = input.State
	addr.ZipCode = input.ZipCode
	addr.Country = country
	if err := r.TenantService.UpdateAddress(ctx, id, addr); err != nil {
		return nil, err
	}
	return addr, nil
}

// MeTenant is the resolver for the meTenant field.
func (r *queryResolver) MeTenant(ctx context.Context) (*model.User, error) {
	userID := sharedctx.UserIDFromCtx(ctx)
	if userID == "" {
		return nil, fmt.Errorf("unauthorized: missing user context")
	}
	aa, err := r.TenantService.GetAssignmentsByUser(ctx, userID)
	if err != nil {
		return nil, err
	}
	return &model.User{ID: userID, Assignments: aa}, nil
}

// Tenant is the resolver for the tenant field.
func (r *queryResolver) Tenant(ctx context.Context, id string) (*db.BunTenant, error) {
	return r.TenantService.GetTenantByID(ctx, id)
}

// Branch is the resolver for the branch field.
func (r *queryResolver) Branch(ctx context.Context, id string) (*db.BunBranch, error) {
	return r.TenantService.GetBranchByID(ctx, id)
}

// Address is the resolver for the address field.
func (r *queryResolver) Address(ctx context.Context, id string) (*db.BunAddress, error) {
	panic(fmt.Errorf("not implemented: Address - address"))
}

// TenantRole is the resolver for the tenantRole field.
// Permissions are loaded lazily via the TenantRole field resolver below.
func (r *queryResolver) TenantRole(ctx context.Context, id string) (*db.BunTenantRole, error) {
	return r.TenantService.GetRoleByID(ctx, id)
}

// TenantPermission is the resolver for the tenantPermission field.
func (r *queryResolver) TenantPermission(ctx context.Context, id string) (*db.BunTenantPermission, error) {
	return r.TenantService.GetPermissionByID(ctx, id)
}

// MyAssignments is the resolver for the myAssignments field.
func (r *queryResolver) MyAssignments(ctx context.Context) ([]*model.TenantUserAssignment, error) {
	userID := sharedctx.UserIDFromCtx(ctx)
	if userID == "" {
		return nil, fmt.Errorf("unauthorized: missing user context")
	}
	return r.TenantService.GetAssignmentsByUser(ctx, userID)
}

// AssignmentsByUser is the resolver for the assignmentsByUser field.
func (r *queryResolver) AssignmentsByUser(ctx context.Context, userID string) ([]*model.TenantUserAssignment, error) {
	return r.TenantService.GetAssignmentsByUser(ctx, userID)
}

// Permissions is the field resolver for TenantRole.permissions.
// Because BunTenantRole has no Permissions field (it is a DB relation),
// gqlgen requires a resolver. This replaces the old inline loading in TenantRole query.
func (r *tenantRoleResolver) Permissions(ctx context.Context, obj *db.BunTenantRole) ([]*db.BunTenantPermission, error) {
	return r.TenantService.GetPermissionsByRole(ctx, obj.ID)
}

// Branch returns generated.BranchResolver implementation.
func (r *Resolver) Branch() generated.BranchResolver { return &branchResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// TenantRole returns generated.TenantRoleResolver implementation.
func (r *Resolver) TenantRole() generated.TenantRoleResolver { return &tenantRoleResolver{r} }

type (
	branchResolver     struct{ *Resolver }
	mutationResolver   struct{ *Resolver }
	queryResolver      struct{ *Resolver }
	tenantRoleResolver struct{ *Resolver }
)
