package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/clinicmanager/services/patient/db"
	"github.com/clinicmanager/services/patient/graph/generated"
)

// FindGoalByID is the resolver for federation entity lookup of Goal.
func (r *entityResolver) FindGoalByID(ctx context.Context, id string) (*db.BunGoal, error) {
	return r.Resolver.PatientService.PatientRepository.FindGoalByID(ctx, id)
}

// FindGuardianByID is the resolver for federation entity lookup of Guardian.
func (r *entityResolver) FindGuardianByID(ctx context.Context, id string) (*db.BunGuardians, error) {
	return r.Resolver.PatientService.PatientRepository.FindGuardianByID(ctx, id)
}

// FindPatientByID is the resolver for federation entity lookup of Patient.
func (r *entityResolver) FindPatientByID(ctx context.Context, id string) (*db.BunPatients, error) {
	return r.Resolver.PatientService.GetPatientByID(ctx, id)
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
