extend type Address @key(fields: "id") {
  id: ID! @external
}

type Patient @key(fields: "id") {
  id: ID!
  tenantId: String!
  branchId: String!
  firstName: String!
  lastName: String!
  dateOfBirth: String!
  gender: String!
  notes: String
  height: String
  weight: String
  isActive: Boolean!
  address: Address
  tag: [PatientTags!]!
  guardian: [Guardian!]!
  goals: [Goal!]!
}

type Goal @key(fields: "id") {
  id: ID!
  patientId: ID!
  goal: String!
  target: String
  progress: Int!
  status: String!
  isActive: Boolean!
}

type PatientTags {
  id: ID!
  name: String!
}

type Guardian @key(fields: "id") {
  id: ID!
  firstName: String!
  lastName: String!
  gender: String!
  email: String
  phone: String!
  notes: String
  isActive: Boolean!
  address: Address
  patient: [Patient!]!
}

input PatientFilter {
  search: String
}

input PatientPagination {
  limit: Int = 10
  offset: Int = 0
}

input PatientsFilter {
  filter: [PatientFilter!]
  pagination: [PatientPagination!]
}

input PatientInput {
  firstName: String!
  lastName: String!
  dateOfBirth: String!
  gender: String!
  notes: String
  height: String
  weight: String
  addressId: ID
}

input PatientUpdateInput {
  firstName: String
  lastName: String
  dateOfBirth: String
  gender: String
  notes: String
  height: String
  weight: String
  addressId: ID
}

input GuardianInput {
  firstName: String!
  lastName: String!
  gender: String!
  email: String
  phone: String
  notes: String
  addressId: ID
}

input GuardianUpdateInput {
  firstName: String
  lastName: String
  gender: String
  email: String
  phone: String
  notes: String
  addressId: ID
}

type PatientGuardianRelationship {
  patientId: ID!
  guardianId: ID!
  relationship: String!
}

type Query {
  patient(id: ID!): Patient
  patients(filter: PatientsFilter): [Patient!]!
  patientsByIds(ids: [ID!]!): [Patient!]!
  patientsForMessaging(search: String!, limit: Int = 10): [Patient!]!
  guardian(id: ID!): Guardian
}

type Mutation {
  createPatient(input: PatientInput!): Patient!
  updatePatient(id: ID!, input: PatientUpdateInput!): Patient!
  deletePatient(id: ID!): Patient!
  inactivatePatient(id: ID!): Patient!
  reactivatePatient(id: ID!): Patient!
  createGuardian(input: GuardianInput!): Guardian!
  updateGuardian(id: ID!, input: GuardianUpdateInput!): Guardian!
  deleteGuardian(id: ID!): Guardian!
  addPatientGuardian(patientId: ID!, guardianId: ID!, relationship: String!): PatientGuardianRelationship!
  updatePatientGuardian(patientId: ID!, guardianId: ID!, relationship: String!): PatientGuardianRelationship!
  removePatientGuardian(patientId: ID!, guardianId: ID!): Boolean!
  createGoal(input: GoalInput!): Goal!
  updateGoal(id: ID!, input: GoalUpdateInput!): Goal!
  deleteGoal(id: ID!): Goal!
}

input GoalInput {
  patientId: ID!
  goal: String!
  target: String
  progress: Int
  status: String
}

input GoalUpdateInput {
  goal: String
  target: String
  progress: Int
  status: String
}
