package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/clinicmanager/services/patient/db"
	"github.com/clinicmanager/services/patient/graph/generated"
	"github.com/clinicmanager/services/patient/graph/model"
)

// Address is the resolver for the address field.
func (r *guardianResolver) Address(ctx context.Context, obj *db.BunGuardians) (*model.Address, error) {
	if obj.AddressID == nil {
		return nil, nil
	}
	return &model.Address{ID: *obj.AddressID}, nil
}

// Patient is the resolver for the patient field.
func (r *guardianResolver) Patient(ctx context.Context, obj *db.BunGuardians) ([]*db.BunPatients, error) {
	return r.Resolver.PatientService.GetGuardianPatients(ctx, obj.ID)
}

// CreatePatient is the resolver for the createPatient field.
func (r *mutationResolver) CreatePatient(ctx context.Context, input model.PatientInput) (*db.BunPatients, error) {
	return r.Resolver.PatientService.CreatePatient(ctx, input)
}

// UpdatePatient is the resolver for the updatePatient field.
func (r *mutationResolver) UpdatePatient(ctx context.Context, id string, input model.PatientUpdateInput) (*db.BunPatients, error) {
	return r.Resolver.PatientService.UpdatePatient(ctx, id, input)
}

// DeletePatient is the resolver for the deletePatient field.
func (r *mutationResolver) DeletePatient(ctx context.Context, id string) (*db.BunPatients, error) {
	return r.Resolver.PatientService.DeletePatient(ctx, id)
}

// InactivatePatient is the resolver for the inactivatePatient field.
func (r *mutationResolver) InactivatePatient(ctx context.Context, id string) (*db.BunPatients, error) {
	return r.Resolver.PatientService.InactivatePatient(ctx, id)
}

// ReactivatePatient is the resolver for the reactivatePatient field.
func (r *mutationResolver) ReactivatePatient(ctx context.Context, id string) (*db.BunPatients, error) {
	return r.Resolver.PatientService.ReactivatePatient(ctx, id)
}

// CreateGuardian is the resolver for the createGuardian field.
func (r *mutationResolver) CreateGuardian(ctx context.Context, input model.GuardianInput) (*db.BunGuardians, error) {
	return r.Resolver.PatientService.CreateGuardian(ctx, input)
}

// UpdateGuardian is the resolver for the updateGuardian field.
func (r *mutationResolver) UpdateGuardian(ctx context.Context, id string, input model.GuardianUpdateInput) (*db.BunGuardians, error) {
	return r.Resolver.PatientService.UpdateGuardian(ctx, id, input)
}

// DeleteGuardian is the resolver for the deleteGuardian field.
func (r *mutationResolver) DeleteGuardian(ctx context.Context, id string) (*db.BunGuardians, error) {
	return r.Resolver.PatientService.DeleteGuardian(ctx, id)
}

// AddPatientGuardian is the resolver for the addPatientGuardian field.
func (r *mutationResolver) AddPatientGuardian(ctx context.Context, patientID string, guardianID string, relationship string) (*model.PatientGuardianRelationship, error) {
	return r.Resolver.PatientService.AddPatientGuardian(ctx, patientID, guardianID, relationship)
}

// UpdatePatientGuardian is the resolver for the updatePatientGuardian field.
func (r *mutationResolver) UpdatePatientGuardian(ctx context.Context, patientID string, guardianID string, relationship string) (*model.PatientGuardianRelationship, error) {
	return r.Resolver.PatientService.UpdatePatientGuardian(ctx, patientID, guardianID, relationship)
}

// RemovePatientGuardian is the resolver for the removePatientGuardian field.
func (r *mutationResolver) RemovePatientGuardian(ctx context.Context, patientID string, guardianID string) (bool, error) {
	return r.Resolver.PatientService.RemovePatientGuardian(ctx, patientID, guardianID)
}

// CreateGoal is the resolver for the createGoal field.
func (r *mutationResolver) CreateGoal(ctx context.Context, input model.GoalInput) (*db.BunGoal, error) {
	return r.Resolver.PatientService.CreateGoal(ctx, input)
}

// UpdateGoal is the resolver for the updateGoal field.
func (r *mutationResolver) UpdateGoal(ctx context.Context, id string, input model.GoalUpdateInput) (*db.BunGoal, error) {
	return r.Resolver.PatientService.UpdateGoal(ctx, id, input)
}

// DeleteGoal is the resolver for the deleteGoal field.
func (r *mutationResolver) DeleteGoal(ctx context.Context, id string) (*db.BunGoal, error) {
	return r.Resolver.PatientService.DeleteGoal(ctx, id)
}

// DateOfBirth is the resolver for the dateOfBirth field.
func (r *patientResolver) DateOfBirth(ctx context.Context, obj *db.BunPatients) (string, error) {
	if obj.DateOfBirth.IsZero() {
		return "", nil
	}
	return obj.DateOfBirth.Format("2006-01-02"), nil
}

// Address is the resolver for the address field.
func (r *patientResolver) Address(ctx context.Context, obj *db.BunPatients) (*model.Address, error) {
	if obj.AddressID == nil {
		return nil, nil
	}
	return &model.Address{ID: *obj.AddressID}, nil
}

// Tag is the resolver for the tag field.
func (r *patientResolver) Tag(ctx context.Context, obj *db.BunPatients) ([]*db.BunPatientTags, error) {
	return r.Resolver.PatientService.GetPatientTags(ctx, obj.ID)
}

// Guardian is the resolver for the guardian field.
func (r *patientResolver) Guardian(ctx context.Context, obj *db.BunPatients) ([]*db.BunGuardians, error) {
	return r.Resolver.PatientService.GetPatientGuardians(ctx, obj.ID)
}

// Goals is the resolver for the goals field.
func (r *patientResolver) Goals(ctx context.Context, obj *db.BunPatients) ([]*db.BunGoal, error) {
	return r.Resolver.PatientService.GetPatientGoals(ctx, obj.ID)
}

// ID is the resolver for the id field.
func (r *patientTagsResolver) ID(ctx context.Context, obj *db.BunPatientTags) (string, error) {
	return obj.TagID, nil
}

// Name is the resolver for the name field.
func (r *patientTagsResolver) Name(ctx context.Context, obj *db.BunPatientTags) (string, error) {
	return obj.TagID, nil
}

// Patient is the resolver for the patient field.
func (r *queryResolver) Patient(ctx context.Context, id string) (*db.BunPatients, error) {
	patient, err := r.Resolver.PatientService.GetPatientByID(ctx, id)
	if err != nil {
		return nil, err
	}

	return patient, nil
}

// Patients is the resolver for the patients field.
func (r *queryResolver) Patients(ctx context.Context, filter *model.PatientsFilter) ([]*db.BunPatients, error) {
	patients, err := r.Resolver.PatientService.ListPatients(ctx, filter)
	if err != nil {
		return nil, err
	}

	return patients, nil
}

// PatientsByIds is the resolver for the patientsByIds field.
func (r *queryResolver) PatientsByIds(ctx context.Context, ids []string) ([]*db.BunPatients, error) {
	return r.Resolver.PatientService.GetPatientsByIDs(ctx, ids)
}

// PatientsForMessaging is the resolver for the patientsForMessaging field.
func (r *queryResolver) PatientsForMessaging(ctx context.Context, search string, limit *int) ([]*db.BunPatients, error) {
	l := 10
	if limit != nil && *limit > 0 {
		l = *limit
	}
	return r.Resolver.PatientService.SearchPatientsForMessaging(ctx, search, l)
}

// Guardian is the resolver for the guardian field.
func (r *queryResolver) Guardian(ctx context.Context, id string) (*db.BunGuardians, error) {
	return r.Resolver.PatientService.GetGuardianByID(ctx, id)
}

// Guardian returns generated.GuardianResolver implementation.
func (r *Resolver) Guardian() generated.GuardianResolver { return &guardianResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Patient returns generated.PatientResolver implementation.
func (r *Resolver) Patient() generated.PatientResolver { return &patientResolver{r} }

// PatientTags returns generated.PatientTagsResolver implementation.
func (r *Resolver) PatientTags() generated.PatientTagsResolver { return &patientTagsResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	guardianResolver    struct{ *Resolver }
	mutationResolver    struct{ *Resolver }
	patientResolver     struct{ *Resolver }
	patientTagsResolver struct{ *Resolver }
	queryResolver       struct{ *Resolver }
)
