DROP TABLE IF EXISTS patient_addresses CASCADE;
DROP TABLE IF EXISTS patient_tags CASCADE;
DROP TABLE IF EXISTS patient_guardians CASCADE;
DROP TABLE IF EXISTS guardians CASCADE;
DROP TABLE IF EXISTS patients CASCADE;
