package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/clinicmanager/services/booking/db"
	"github.com/clinicmanager/services/booking/graph/generated"
)

// FindAppointmentByID is the resolver for the findAppointmentByID field.
func (r *entityResolver) FindAppointmentByID(ctx context.Context, id string) (*db.BunAppointment, error) {
	return r.BookingService.GetAppointmentByID(ctx, id)
}

// FindAppointmentSlotByID is the resolver for the findAppointmentSlotByID field.
func (r *entityResolver) FindAppointmentSlotByID(ctx context.Context, id string) (*db.BunAppointmentSlot, error) {
	return r.BookingService.GetAppointmentSlotByID(ctx, id)
}

// FindBranchHoursByID is the resolver for the findBranchHoursByID field.
func (r *entityResolver) FindBranchHoursByID(ctx context.Context, id string) (*db.BunBranchHours, error) {
	return r.BookingService.GetBranchHoursByID(ctx, id)
}

// FindPractitionerAvailabilityByID is the resolver for the findPractitionerAvailabilityByID field.
func (r *entityResolver) FindPractitionerAvailabilityByID(ctx context.Context, id string) (*db.BunPractitionerAvailability, error) {
	return r.BookingService.GetPractitionerAvailabilityByID(ctx, id)
}

// FindPractitionerBranchByID is the resolver for the findPractitionerBranchByID field.
func (r *entityResolver) FindPractitionerBranchByID(ctx context.Context, id string) (*db.BunPractitionerBranch, error) {
	return r.BookingService.GetPractitionerBranchByID(ctx, id)
}

// FindScheduleExceptionByID is the resolver for the findScheduleExceptionByID field.
func (r *entityResolver) FindScheduleExceptionByID(ctx context.Context, id string) (*db.BunScheduleException, error) {
	return r.BookingService.GetScheduleExceptionByID(ctx, id)
}

// FindScheduleTemplateByID is the resolver for the findScheduleTemplateByID field.
func (r *entityResolver) FindScheduleTemplateByID(ctx context.Context, id string) (*db.BunScheduleTemplate, error) {
	return r.BookingService.GetScheduleTemplateByID(ctx, id)
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
