package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"
	"time"

	"github.com/clinicmanager/services/booking/db"
	"github.com/clinicmanager/services/booking/graph/generated"
	"github.com/clinicmanager/services/booking/graph/model"
)

// ScheduledStart is the resolver for the scheduled_start field.
func (r *appointmentResolver) ScheduledStart(ctx context.Context, obj *db.BunAppointment) (string, error) {
	return obj.StartAt.Format(time.RFC3339), nil
}

// ScheduledEnd is the resolver for the scheduled_end field.
func (r *appointmentResolver) ScheduledEnd(ctx context.Context, obj *db.BunAppointment) (string, error) {
	return obj.EndAt.Format(time.RFC3339), nil
}

// Note is the resolver for the note field.
func (r *appointmentResolver) Note(ctx context.Context, obj *db.BunAppointment) (*string, error) {
	if obj.Notes == "" {
		return nil, nil
	}
	return &obj.Notes, nil
}

// SlotID is the resolver for the slot_id field.
func (r *appointmentResolver) SlotID(ctx context.Context, obj *db.BunAppointment) (*string, error) {
	return obj.AppointmentSlotID, nil
}

// CancelledAt is the resolver for the cancelled_at field.
func (r *appointmentResolver) CancelledAt(ctx context.Context, obj *db.BunAppointment) (*string, error) {
	panic(fmt.Errorf("not implemented: CancelledAt - cancelled_at"))
}

// CreatedAt is the resolver for the created_at field.
func (r *appointmentResolver) CreatedAt(ctx context.Context, obj *db.BunAppointment) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *appointmentResolver) UpdatedAt(ctx context.Context, obj *db.BunAppointment) (*string, error) {
	if obj.UpdatedAt.IsZero() {
		return nil, nil
	}
	s := obj.UpdatedAt.Format(time.RFC3339)
	return &s, nil
}

// Practitioner is the resolver for the practitioner field.
func (r *appointmentResolver) Practitioner(ctx context.Context, obj *db.BunAppointment) (*model.User, error) {
	if obj.PractitionerID == nil {
		return nil, nil
	}
	return &model.User{ID: *obj.PractitionerID}, nil
}

// Patient is the resolver for the patient field.
func (r *appointmentResolver) Patient(ctx context.Context, obj *db.BunAppointment) (*model.Patient, error) {
	if obj.PatientID == nil {
		return nil, nil
	}
	return &model.Patient{ID: *obj.PatientID}, nil
}

// Goals is the resolver for the goals field.
func (r *appointmentResolver) Goals(ctx context.Context, obj *db.BunAppointment) ([]*db.BunAppointmentGoal, error) {
	return r.BookingService.GetAppointmentGoals(ctx, obj.ID)
}

// Soap is the resolver for the soap field.
func (r *appointmentResolver) Soap(ctx context.Context, obj *db.BunAppointment) (*db.BunSoapNote, error) {
	return r.BookingService.GetAppointmentSoap(ctx, obj.ID)
}

// CreatedAt is the resolver for the created_at field.
func (r *appointmentGoalResolver) CreatedAt(ctx context.Context, obj *db.BunAppointmentGoal) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *appointmentGoalResolver) UpdatedAt(ctx context.Context, obj *db.BunAppointmentGoal) (*string, error) {
	if obj.UpdatedAt.IsZero() {
		return nil, nil
	}
	s := obj.UpdatedAt.Format(time.RFC3339)
	return &s, nil
}

// Goal is the resolver for the goal field.
func (r *appointmentGoalResolver) Goal(ctx context.Context, obj *db.BunAppointmentGoal) (*model.Goal, error) {
	return &model.Goal{ID: obj.GoalID}, nil
}

// SlotDate is the resolver for the slot_date field.
func (r *appointmentSlotResolver) SlotDate(ctx context.Context, obj *db.BunAppointmentSlot) (string, error) {
	return obj.StartAt.Format("2006-01-02"), nil
}

// SlotStart is the resolver for the slot_start field.
func (r *appointmentSlotResolver) SlotStart(ctx context.Context, obj *db.BunAppointmentSlot) (string, error) {
	return obj.StartAt.Format(time.RFC3339), nil
}

// SlotEnd is the resolver for the slot_end field.
func (r *appointmentSlotResolver) SlotEnd(ctx context.Context, obj *db.BunAppointmentSlot) (string, error) {
	return obj.EndAt.Format(time.RFC3339), nil
}

// AppointmentID is the resolver for the appointment_id field.
func (r *appointmentSlotResolver) AppointmentID(ctx context.Context, obj *db.BunAppointmentSlot) (*string, error) {
	return nil, nil
}

// CreatedAt is the resolver for the created_at field.
func (r *appointmentSlotResolver) CreatedAt(ctx context.Context, obj *db.BunAppointmentSlot) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *appointmentSlotResolver) UpdatedAt(ctx context.Context, obj *db.BunAppointmentSlot) (*string, error) {
	if obj.UpdatedAt.IsZero() {
		return nil, nil
	}
	s := obj.UpdatedAt.Format(time.RFC3339)
	return &s, nil
}

// Practitioner is the resolver for the practitioner field.
func (r *appointmentSlotResolver) Practitioner(ctx context.Context, obj *db.BunAppointmentSlot) (*model.User, error) {
	if obj.PractitionerID == nil {
		return nil, nil
	}
	return &model.User{ID: *obj.PractitionerID}, nil
}

// DayOfWeek is the resolver for the day_of_week field.
func (r *branchHoursResolver) DayOfWeek(ctx context.Context, obj *db.BunBranchHours) (int, error) {
	days := []string{"MO", "TU", "WE", "TH", "FR", "SA", "SU"}
	for i, d := range days {
		for j := 0; j < len(obj.RecurrenceRule)-1; j++ {
			if obj.RecurrenceRule[j:j+2] == d {
				return i, nil
			}
		}
	}
	return 0, nil
}

// OpenTime is the resolver for the open_time field.
func (r *branchHoursResolver) OpenTime(ctx context.Context, obj *db.BunBranchHours) (*string, error) {
	if obj.OpenTime.IsZero() {
		return nil, nil
	}
	s := obj.OpenTime.Format("15:04")
	return &s, nil
}

// CloseTime is the resolver for the close_time field.
func (r *branchHoursResolver) CloseTime(ctx context.Context, obj *db.BunBranchHours) (*string, error) {
	if obj.CloseTime.IsZero() {
		return nil, nil
	}
	s := obj.CloseTime.Format("15:04")
	return &s, nil
}

// CreatedAt is the resolver for the created_at field.
func (r *branchHoursResolver) CreatedAt(ctx context.Context, obj *db.BunBranchHours) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *branchHoursResolver) UpdatedAt(ctx context.Context, obj *db.BunBranchHours) (*string, error) {
	if obj.UpdatedAt.IsZero() {
		return nil, nil
	}
	s := obj.UpdatedAt.Format(time.RFC3339)
	return &s, nil
}

// CreateBranchHours is the resolver for the createBranchHours field.
func (r *mutationResolver) CreateBranchHours(ctx context.Context, input model.BranchHoursInput) (*db.BunBranchHours, error) {
	return r.BookingService.CreateBranchHours(ctx, input)
}

// UpdateBranchHours is the resolver for the updateBranchHours field.
func (r *mutationResolver) UpdateBranchHours(ctx context.Context, id string, input model.BranchHoursUpdateInput) (*db.BunBranchHours, error) {
	return r.BookingService.UpdateBranchHours(ctx, id, input)
}

// DeleteBranchHours is the resolver for the deleteBranchHours field.
func (r *mutationResolver) DeleteBranchHours(ctx context.Context, id string) (bool, error) {
	return r.BookingService.DeleteBranchHours(ctx, id)
}

// CreatePractitionerBranch is the resolver for the createPractitionerBranch field.
func (r *mutationResolver) CreatePractitionerBranch(ctx context.Context, input model.PractitionerBranchInput) (*db.BunPractitionerBranch, error) {
	return r.BookingService.CreatePractitionerBranch(ctx, input)
}

// DeletePractitionerBranch is the resolver for the deletePractitionerBranch field.
func (r *mutationResolver) DeletePractitionerBranch(ctx context.Context, id string) (bool, error) {
	return r.BookingService.DeletePractitionerBranch(ctx, id)
}

// CreatePractitionerAvailability is the resolver for the createPractitionerAvailability field.
func (r *mutationResolver) CreatePractitionerAvailability(ctx context.Context, input model.PractitionerAvailabilityInput) (*db.BunPractitionerAvailability, error) {
	return r.BookingService.CreatePractitionerAvailability(ctx, input)
}

// DeletePractitionerAvailability is the resolver for the deletePractitionerAvailability field.
func (r *mutationResolver) DeletePractitionerAvailability(ctx context.Context, id string) (bool, error) {
	return r.BookingService.DeletePractitionerAvailability(ctx, id)
}

// CreateScheduleTemplate is the resolver for the createScheduleTemplate field.
func (r *mutationResolver) CreateScheduleTemplate(ctx context.Context, input model.ScheduleTemplateInput) (*db.BunScheduleTemplate, error) {
	return r.BookingService.CreateScheduleTemplate(ctx, input)
}

// UpdateScheduleTemplate is the resolver for the updateScheduleTemplate field.
func (r *mutationResolver) UpdateScheduleTemplate(ctx context.Context, id string, input model.ScheduleTemplateUpdateInput) (*db.BunScheduleTemplate, error) {
	return r.BookingService.UpdateScheduleTemplate(ctx, id, input)
}

// DeleteScheduleTemplate is the resolver for the deleteScheduleTemplate field.
func (r *mutationResolver) DeleteScheduleTemplate(ctx context.Context, id string) (bool, error) {
	return r.BookingService.DeleteScheduleTemplate(ctx, id)
}

// GenerateSlots is the resolver for the generateSlots field.
func (r *mutationResolver) GenerateSlots(ctx context.Context, branchID string, practitionerID string, date string) ([]*db.BunAppointmentSlot, error) {
	return r.BookingService.GenerateSlots(ctx, branchID, practitionerID, date)
}

// UpdateSlotStatus is the resolver for the updateSlotStatus field.
func (r *mutationResolver) UpdateSlotStatus(ctx context.Context, id string, status string) (*db.BunAppointmentSlot, error) {
	return r.BookingService.UpdateSlotStatus(ctx, id, status)
}

// CreateAppointment is the resolver for the createAppointment field.
func (r *mutationResolver) CreateAppointment(ctx context.Context, input model.AppointmentInput) (*db.BunAppointment, error) {
	return r.BookingService.CreateAppointment(ctx, input)
}

// UpdateAppointment is the resolver for the updateAppointment field.
func (r *mutationResolver) UpdateAppointment(ctx context.Context, id string, input model.AppointmentUpdateInput) (*db.BunAppointment, error) {
	return r.BookingService.UpdateAppointment(ctx, id, input)
}

// ConfirmAppointment is the resolver for the confirmAppointment field.
func (r *mutationResolver) ConfirmAppointment(ctx context.Context, id string) (*db.BunAppointment, error) {
	return r.BookingService.ConfirmAppointment(ctx, id)
}

// StartAppointment is the resolver for the startAppointment field.
func (r *mutationResolver) StartAppointment(ctx context.Context, id string, goalIds []string) (*db.BunAppointment, error) {
	return r.BookingService.StartAppointment(ctx, id, goalIds)
}

// CompleteAppointment is the resolver for the completeAppointment field.
func (r *mutationResolver) CompleteAppointment(ctx context.Context, id string) (*db.BunAppointment, error) {
	return r.BookingService.CompleteAppointment(ctx, id)
}

// CancelAppointment is the resolver for the cancelAppointment field.
func (r *mutationResolver) CancelAppointment(ctx context.Context, id string, input model.CancelAppointmentInput) (*db.BunAppointment, error) {
	return r.BookingService.CancelAppointment(ctx, id, input.Reason)
}

// RescheduleAppointment is the resolver for the rescheduleAppointment field.
func (r *mutationResolver) RescheduleAppointment(ctx context.Context, id string, input model.RescheduleAppointmentInput) (*db.BunAppointment, error) {
	return r.BookingService.RescheduleAppointment(ctx, id, input)
}

// SetAppointmentGoals is the resolver for the setAppointmentGoals field.
func (r *mutationResolver) SetAppointmentGoals(ctx context.Context, appointmentID string, goalIds []string) ([]*db.BunAppointmentGoal, error) {
	return r.BookingService.SetAppointmentGoals(ctx, appointmentID, goalIds)
}

// UpdateAppointmentGoal is the resolver for the updateAppointmentGoal field.
func (r *mutationResolver) UpdateAppointmentGoal(ctx context.Context, id string, input model.AppointmentGoalUpdateInput) (*db.BunAppointmentGoal, error) {
	return r.BookingService.UpdateAppointmentGoal(ctx, id, input)
}

// RemoveAppointmentGoal is the resolver for the removeAppointmentGoal field.
func (r *mutationResolver) RemoveAppointmentGoal(ctx context.Context, id string) (bool, error) {
	return r.BookingService.RemoveAppointmentGoal(ctx, id)
}

// UpsertSoapNote is the resolver for the upsertSoapNote field.
func (r *mutationResolver) UpsertSoapNote(ctx context.Context, appointmentID string, input model.SoapNoteInput) (*db.BunSoapNote, error) {
	return r.BookingService.UpsertSoapNote(ctx, appointmentID, input)
}

// CreateScheduleException is the resolver for the createScheduleException field.
func (r *mutationResolver) CreateScheduleException(ctx context.Context, input model.ScheduleExceptionInput) (*db.BunScheduleException, error) {
	return r.BookingService.CreateScheduleException(ctx, input)
}

// DeleteScheduleException is the resolver for the deleteScheduleException field.
func (r *mutationResolver) DeleteScheduleException(ctx context.Context, id string) (bool, error) {
	return r.BookingService.DeleteScheduleException(ctx, id)
}

// BranchID is the resolver for the branch_id field.
func (r *practitionerAvailabilityResolver) BranchID(ctx context.Context, obj *db.BunPractitionerAvailability) (string, error) {
	return "", nil
}

// StartTime is the resolver for the start_time field.
func (r *practitionerAvailabilityResolver) StartTime(ctx context.Context, obj *db.BunPractitionerAvailability) (string, error) {
	return obj.AvailableFrom.Format(time.RFC3339), nil
}

// EndTime is the resolver for the end_time field.
func (r *practitionerAvailabilityResolver) EndTime(ctx context.Context, obj *db.BunPractitionerAvailability) (string, error) {
	return obj.AvailableTo.Format(time.RFC3339), nil
}

// CreatedAt is the resolver for the created_at field.
func (r *practitionerAvailabilityResolver) CreatedAt(ctx context.Context, obj *db.BunPractitionerAvailability) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *practitionerAvailabilityResolver) UpdatedAt(ctx context.Context, obj *db.BunPractitionerAvailability) (*string, error) {
	if obj.UpdatedAt.IsZero() {
		return nil, nil
	}
	s := obj.UpdatedAt.Format(time.RFC3339)
	return &s, nil
}

// Practitioner is the resolver for the practitioner field.
func (r *practitionerAvailabilityResolver) Practitioner(ctx context.Context, obj *db.BunPractitionerAvailability) (*model.User, error) {
	return &model.User{ID: obj.PractitionerID}, nil
}

// CreatedAt is the resolver for the created_at field.
func (r *practitionerBranchResolver) CreatedAt(ctx context.Context, obj *db.BunPractitionerBranch) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *practitionerBranchResolver) UpdatedAt(ctx context.Context, obj *db.BunPractitionerBranch) (*string, error) {
	if obj.UpdatedAt.IsZero() {
		return nil, nil
	}
	s := obj.UpdatedAt.Format(time.RFC3339)
	return &s, nil
}

// Practitioner is the resolver for the practitioner field.
func (r *practitionerBranchResolver) Practitioner(ctx context.Context, obj *db.BunPractitionerBranch) (*model.User, error) {
	return &model.User{ID: obj.PractitionerID}, nil
}

// BranchHour is the resolver for the branchHour field.
func (r *queryResolver) BranchHour(ctx context.Context, id string) (*db.BunBranchHours, error) {
	return r.BookingService.GetBranchHoursByID(ctx, id)
}

// BranchHours is the resolver for the branchHours field.
func (r *queryResolver) BranchHours(ctx context.Context, branchID *string) ([]*db.BunBranchHours, error) {
	if branchID != nil && *branchID != "" {
		return r.BookingService.GetBranchHoursByBranch(ctx, *branchID)
	}
	return r.BookingService.ListBranchHours(ctx)
}

// PractitionerBranch is the resolver for the practitionerBranch field.
func (r *queryResolver) PractitionerBranch(ctx context.Context, id string) (*db.BunPractitionerBranch, error) {
	return r.BookingService.GetPractitionerBranchByID(ctx, id)
}

// PractitionerBranches is the resolver for the practitionerBranches field.
func (r *queryResolver) PractitionerBranches(ctx context.Context, branchID *string, role *string) ([]*db.BunPractitionerBranch, error) {
	if branchID != nil && *branchID != "" {
		roleFilter := ""
		if role != nil {
			roleFilter = *role
		}
		return r.BookingService.GetPractitionerBranchesByBranch(ctx, *branchID, roleFilter)
	}
	return r.BookingService.ListPractitionerBranches(ctx)
}

// PractitionerAvailability is the resolver for the practitionerAvailability field.
func (r *queryResolver) PractitionerAvailability(ctx context.Context, id string) (*db.BunPractitionerAvailability, error) {
	return r.BookingService.GetPractitionerAvailabilityByID(ctx, id)
}

// PractitionerAvailabilities is the resolver for the practitionerAvailabilities field.
func (r *queryResolver) PractitionerAvailabilities(ctx context.Context, branchID *string, practitionerID *string) ([]*db.BunPractitionerAvailability, error) {
	return r.BookingService.GetPractitionerAvailabilities(ctx, branchID, practitionerID)
}

// ScheduleTemplate is the resolver for the scheduleTemplate field.
func (r *queryResolver) ScheduleTemplate(ctx context.Context, id string) (*db.BunScheduleTemplate, error) {
	return r.BookingService.GetScheduleTemplateByID(ctx, id)
}

// ScheduleTemplates is the resolver for the scheduleTemplates field.
func (r *queryResolver) ScheduleTemplates(ctx context.Context, branchID *string, practitionerID *string) ([]*db.BunScheduleTemplate, error) {
	return r.BookingService.GetScheduleTemplates(ctx, branchID, practitionerID)
}

// AppointmentSlot is the resolver for the appointmentSlot field.
func (r *queryResolver) AppointmentSlot(ctx context.Context, id string) (*db.BunAppointmentSlot, error) {
	return r.BookingService.GetAppointmentSlotByID(ctx, id)
}

// AppointmentSlots is the resolver for the appointmentSlots field.
func (r *queryResolver) AppointmentSlots(ctx context.Context, filter model.AppointmentSlotsFilter) ([]*db.BunAppointmentSlot, error) {
	return r.BookingService.GetAppointmentSlots(ctx, filter)
}

// Appointment is the resolver for the appointment field.
func (r *queryResolver) Appointment(ctx context.Context, id string) (*db.BunAppointment, error) {
	return r.BookingService.GetAppointmentByID(ctx, id)
}

// Appointments is the resolver for the appointments field.
func (r *queryResolver) Appointments(ctx context.Context, filter model.AppointmentsFilter) ([]*db.BunAppointment, error) {
	return r.BookingService.GetAppointments(ctx, filter)
}

// ScheduleException is the resolver for the scheduleException field.
func (r *queryResolver) ScheduleException(ctx context.Context, id string) (*db.BunScheduleException, error) {
	return r.BookingService.GetScheduleExceptionByID(ctx, id)
}

// ScheduleExceptions is the resolver for the scheduleExceptions field.
func (r *queryResolver) ScheduleExceptions(ctx context.Context, branchID *string, practitionerID *string) ([]*db.BunScheduleException, error) {
	return r.BookingService.GetScheduleExceptions(ctx, branchID, practitionerID)
}

// BranchID is the resolver for the branch_id field.
func (r *scheduleExceptionResolver) BranchID(ctx context.Context, obj *db.BunScheduleException) (string, error) {
	return "", nil
}

// ExceptionDate is the resolver for the exception_date field.
func (r *scheduleExceptionResolver) ExceptionDate(ctx context.Context, obj *db.BunScheduleException) (string, error) {
	return obj.StartAt.Format("2006-01-02"), nil
}

// CreatedAt is the resolver for the created_at field.
func (r *scheduleExceptionResolver) CreatedAt(ctx context.Context, obj *db.BunScheduleException) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *scheduleExceptionResolver) UpdatedAt(ctx context.Context, obj *db.BunScheduleException) (*string, error) {
	if obj.UpdatedAt.IsZero() {
		return nil, nil
	}
	s := obj.UpdatedAt.Format(time.RFC3339)
	return &s, nil
}

// Practitioner is the resolver for the practitioner field.
func (r *scheduleExceptionResolver) Practitioner(ctx context.Context, obj *db.BunScheduleException) (*model.User, error) {
	if obj.PractitionerID == nil {
		return nil, nil
	}
	return &model.User{ID: *obj.PractitionerID}, nil
}

// TemplateName is the resolver for the template_name field.
func (r *scheduleTemplateResolver) TemplateName(ctx context.Context, obj *db.BunScheduleTemplate) (string, error) {
	return fmt.Sprintf("Schedule %s", obj.ID[:8]), nil
}

// DayOfWeek is the resolver for the day_of_week field.
func (r *scheduleTemplateResolver) DayOfWeek(ctx context.Context, obj *db.BunScheduleTemplate) (int, error) {
	days := []string{"MO", "TU", "WE", "TH", "FR", "SA", "SU"}
	for i, d := range days {
		for j := 0; j < len(obj.RecurrenceRule)-1; j++ {
			if obj.RecurrenceRule[j:j+2] == d {
				return i, nil
			}
		}
	}
	return 0, nil
}

// StartTime is the resolver for the start_time field.
func (r *scheduleTemplateResolver) StartTime(ctx context.Context, obj *db.BunScheduleTemplate) (string, error) {
	return obj.StartTime.Format("15:04"), nil
}

// EndTime is the resolver for the end_time field.
func (r *scheduleTemplateResolver) EndTime(ctx context.Context, obj *db.BunScheduleTemplate) (string, error) {
	return obj.EndTime.Format("15:04"), nil
}

// SlotDurationMinutes is the resolver for the slot_duration_minutes field.
func (r *scheduleTemplateResolver) SlotDurationMinutes(ctx context.Context, obj *db.BunScheduleTemplate) (int, error) {
	return obj.SlotDuration, nil
}

// BreakStart is the resolver for the break_start field.
func (r *scheduleTemplateResolver) BreakStart(ctx context.Context, obj *db.BunScheduleTemplate) (*string, error) {
	return nil, nil
}

// BreakEnd is the resolver for the break_end field.
func (r *scheduleTemplateResolver) BreakEnd(ctx context.Context, obj *db.BunScheduleTemplate) (*string, error) {
	return nil, nil
}

// CreatedAt is the resolver for the created_at field.
func (r *scheduleTemplateResolver) CreatedAt(ctx context.Context, obj *db.BunScheduleTemplate) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *scheduleTemplateResolver) UpdatedAt(ctx context.Context, obj *db.BunScheduleTemplate) (*string, error) {
	if obj.UpdatedAt.IsZero() {
		return nil, nil
	}
	s := obj.UpdatedAt.Format(time.RFC3339)
	return &s, nil
}

// Practitioner is the resolver for the practitioner field.
func (r *scheduleTemplateResolver) Practitioner(ctx context.Context, obj *db.BunScheduleTemplate) (*model.User, error) {
	if obj.PractitionerID == nil {
		return nil, nil
	}
	return &model.User{ID: *obj.PractitionerID}, nil
}

// CreatedAt is the resolver for the created_at field.
func (r *soapNoteResolver) CreatedAt(ctx context.Context, obj *db.BunSoapNote) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *soapNoteResolver) UpdatedAt(ctx context.Context, obj *db.BunSoapNote) (*string, error) {
	if obj.UpdatedAt.IsZero() {
		return nil, nil
	}
	s := obj.UpdatedAt.Format(time.RFC3339)
	return &s, nil
}

// Appointment returns generated.AppointmentResolver implementation.
func (r *Resolver) Appointment() generated.AppointmentResolver { return &appointmentResolver{r} }

// AppointmentGoal returns generated.AppointmentGoalResolver implementation.
func (r *Resolver) AppointmentGoal() generated.AppointmentGoalResolver {
	return &appointmentGoalResolver{r}
}

// AppointmentSlot returns generated.AppointmentSlotResolver implementation.
func (r *Resolver) AppointmentSlot() generated.AppointmentSlotResolver {
	return &appointmentSlotResolver{r}
}

// BranchHours returns generated.BranchHoursResolver implementation.
func (r *Resolver) BranchHours() generated.BranchHoursResolver { return &branchHoursResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// PractitionerAvailability returns generated.PractitionerAvailabilityResolver implementation.
func (r *Resolver) PractitionerAvailability() generated.PractitionerAvailabilityResolver {
	return &practitionerAvailabilityResolver{r}
}

// PractitionerBranch returns generated.PractitionerBranchResolver implementation.
func (r *Resolver) PractitionerBranch() generated.PractitionerBranchResolver {
	return &practitionerBranchResolver{r}
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// ScheduleException returns generated.ScheduleExceptionResolver implementation.
func (r *Resolver) ScheduleException() generated.ScheduleExceptionResolver {
	return &scheduleExceptionResolver{r}
}

// ScheduleTemplate returns generated.ScheduleTemplateResolver implementation.
func (r *Resolver) ScheduleTemplate() generated.ScheduleTemplateResolver {
	return &scheduleTemplateResolver{r}
}

// SoapNote returns generated.SoapNoteResolver implementation.
func (r *Resolver) SoapNote() generated.SoapNoteResolver { return &soapNoteResolver{r} }

type (
	appointmentResolver              struct{ *Resolver }
	appointmentGoalResolver          struct{ *Resolver }
	appointmentSlotResolver          struct{ *Resolver }
	branchHoursResolver              struct{ *Resolver }
	mutationResolver                 struct{ *Resolver }
	practitionerAvailabilityResolver struct{ *Resolver }
	practitionerBranchResolver       struct{ *Resolver }
	queryResolver                    struct{ *Resolver }
	scheduleExceptionResolver        struct{ *Resolver }
	scheduleTemplateResolver         struct{ *Resolver }
	soapNoteResolver                 struct{ *Resolver }
)
