// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GuardianInput struct {
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Gender    string  `json:"gender"`
	Email     *string `json:"email,omitempty"`
	Phone     *string `json:"phone,omitempty"`
	Notes     *string `json:"notes,omitempty"`
}

type GuardianUpdateInput struct {
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Gender    *string `json:"gender,omitempty"`
	Email     *string `json:"email,omitempty"`
	Phone     *string `json:"phone,omitempty"`
	Notes     *string `json:"notes,omitempty"`
}

type Mutation struct {
}

type PatientAddressInput struct {
	Address   string `json:"address"`
	Baranggay string `json:"baranggay"`
	City      string `json:"city"`
	State     string `json:"state"`
	ZipCode   string `json:"zipCode"`
	Country   string `json:"country"`
}

type PatientFilter struct {
	Search *string `json:"search,omitempty"`
}

type PatientGuardianRelationship struct {
	PatientID    string `json:"patientId"`
	GuardianID   string `json:"guardianId"`
	Relationship string `json:"relationship"`
}

type PatientInput struct {
	FirstName   string               `json:"firstName"`
	LastName    string               `json:"lastName"`
	DateOfBirth string               `json:"dateOfBirth"`
	Gender      string               `json:"gender"`
	Notes       *string              `json:"notes,omitempty"`
	Height      *string              `json:"height,omitempty"`
	Weight      *string              `json:"weight,omitempty"`
	Address     *PatientAddressInput `json:"address"`
}

type PatientPagination struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type PatientUpdateInput struct {
	FirstName   *string              `json:"firstName,omitempty"`
	LastName    *string              `json:"lastName,omitempty"`
	DateOfBirth *string              `json:"dateOfBirth,omitempty"`
	Gender      *string              `json:"gender,omitempty"`
	Notes       *string              `json:"notes,omitempty"`
	Height      *string              `json:"height,omitempty"`
	Weight      *string              `json:"weight,omitempty"`
	Address     *PatientAddressInput `json:"address,omitempty"`
}

type PatientsFilter struct {
	Filter     []*PatientFilter     `json:"filter,omitempty"`
	Pagination []*PatientPagination `json:"pagination,omitempty"`
}

type Query struct {
}
