// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Permission struct {
	ID       string `json:"id"`
	Resource string `json:"resource"`
	Action   string `json:"action"`
	Scope    string `json:"scope"`
}

type Query struct {
}

type Role struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Description *string       `json:"description,omitempty"`
	Permissions []*Permission `json:"permissions"`
}

type User struct {
	ID          string                  `json:"id"`
	Email       string                  `json:"email"`
	Name        string                  `json:"name"`
	IsActive    bool                    `json:"isActive"`
	LastLogin   *string                 `json:"lastLogin,omitempty"`
	Assignments []*UserBranchAssignment `json:"assignments"`
}

func (User) IsEntity() {}

type UserBranchAssignment struct {
	ID         string `json:"id"`
	UserID     string `json:"userId"`
	BranchID   string `json:"branchId"`
	TenantID   string `json:"tenantId"`
	Role       *Role  `json:"role"`
	AssignedBy string `json:"assignedBy"`
	AssignedAt string `json:"assignedAt"`
	IsActive   bool   `json:"isActive"`
}
