// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AppRole struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	Description   *string `json:"description,omitempty"`
	CreatedAt     string  `json:"createdAt"`
	CreatedBy     *string `json:"createdBy,omitempty"`
	CreatedAction *string `json:"createdAction,omitempty"`
	UpdatedAt     *string `json:"updatedAt,omitempty"`
	UpdatedBy     *string `json:"updatedBy,omitempty"`
	UpdatedAction *string `json:"updatedAction,omitempty"`
}

func (AppRole) IsEntity() {}

type Query struct {
}

type User struct {
	ID            string     `json:"id"`
	Email         string     `json:"email"`
	Name          string     `json:"name"`
	IsActive      bool       `json:"isActive"`
	LastLogin     *string    `json:"lastLogin,omitempty"`
	AppRoles      []*AppRole `json:"appRoles"`
	IsValidated   bool       `json:"isValidated"`
	ValidatedAt   *string    `json:"validatedAt,omitempty"`
	CreatedAt     string     `json:"createdAt"`
	UpdatedAt     string     `json:"updatedAt"`
	CreatedBy     *string    `json:"createdBy,omitempty"`
	UpdatedBy     *string    `json:"updatedBy,omitempty"`
	CreatedAction *string    `json:"createdAction,omitempty"`
	UpdatedAction *string    `json:"updatedAction,omitempty"`
}

func (User) IsEntity() {}
